### ISSUE TITLE
Ingress should also expose UDP port 51820 right?

### ISSUE THREAD

**Issue by nodesocket** [brandon099/wg-easy-helm-chart#5]
Shouldn't the ingress definition at https://github.com/brandon099/wg-easy-helm-chart/blob/main/charts/wg-easy/templates/ingress.yaml also expose `UDP 51820`?

My problem is the web dashboard has an ingress which is great and working as expected, but I believe the service `wg-easy-wg` also needs to be exposed outside of Kubernetes right?

```
pi@kube-master:~ $ kubectl get services
NAME          TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
kubernetes    ClusterIP      10.96.0.1       <none>        443/TCP                      87d
traefik       LoadBalancer   10.103.222.27   10.0.0.90     80:30041/TCP,443:30133/TCP   21h
wg-easy-web   ClusterIP      10.105.230.37   <none>        51821/TCP                    21h
wg-easy-wg    ClusterIP      10.103.58.64    <none>        51820/UDP                    21h

pi@kube-master:~ $ kubectl get ingress
NAME      CLASS    HOSTS                ADDRESS   PORTS     AGE
wg-easy   <none>   vpn.hooli.xyz             80, 443   21h
```

**Comment by brandon099** [comment]
I have [MetalLB](https://metallb.universe.tf/) set up and the wg-easy-wg service as `type: LoadBalancer`, so it gets an "external IP" my network can route to. This allows me to port forward from my router to that IP associated with the wg-easy-wg external IP to UDP 51820.

```bash
NAME                       TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)
wg-easy-wg                 LoadBalancer   10.43.217.100   10.0.6.10   51820:31750/UDP
```

**Comment by fpiesche** [comment]
Additionally, Nginx Ingress resources can't actually expose raw TCP/UDP sockets; doing this with the nginx ingress controller requires setting the relevant ports up in a ConfigMap rather than on the Ingress.
